# Experiment Parameters
name: "test"
path_to_runs_folder:

# DataUnits
data_units:
  doy:
    class: h2ox.ai.dataset.data_units.SynthTrigDoY
    site_keys:
      - kabini
      - harangi
      - bhadra
      - hemavathy
      - lower_bhawani
      - krishnaraja_sagar
    sin_or_cos: [sin,cos]
    start_step: 0
    end_step: 90
    step_size: 1
  forecast:
    class: h2ox.ai.dataset.data_units.ZRSpatialDataUnit
    variable_keys: [t2m,tp]
    gdf_path: /home/jupyter/h2ox-ai/data/basins.geojson
    site_col: DAM_NAME
    site_keys:
      - kabini
      - harangi
      - bhadra
      - hemavathy
      - lower_bhawani
      - krishnaraja_sagar
    datetime_col: time
    z_address: gs://oxeo-forecasts/ecmwf-forecast
    steps_key: step
    steps: null
    zarr_mapper: h2ox.ai.dataset.utils.gcsfs_mapper
    lat_col: latitude
    lon_col: longitude
  historic:
    class: h2ox.ai.dataset.data_units.ZRSpatialDataUnit
    variable_keys: [t2m,tp]
    gdf_path: /home/jupyter/h2ox-ai/data/basins.geojson
    site_col: DAM_NAME
    site_keys:
      - kabini
      - harangi
      - bhadra
      - hemavathy
      - lower_bhawani
      - krishnaraja_sagar
    datetime_col: time
    z_address: gs://oxeo-era5/build
    steps_key: null
    steps: null
    zarr_mapper: h2ox.ai.dataset.utils.gcsfs_mapper
    lat_col: latitude
    lon_col: longitude
  targets:
    class: h2ox.ai.dataset.data_units.BQDataUnit
    variable_keys: [DATETIME, WATER_VOLUME, RESERVOIR_NAME]
    site_col: RESERVOIR_NAME
    datetime_col: DATETIME
    bq_address: oxeo-main.wave2web.reservoir-data
    site_keys:
      - kabini
      - harangi
      - bhadra
      - hemavathy
      - lower_bhawani
      - krishnaraja_sagar

# Data Parameters
pytorch_dataset: h2ox.ai.dataset.dataset.FcastDataset
normalize: false
seq_len: 60
future_horizon: 76
encode_doy: true
include_ohe: true
sites:
  - "kabini"                                     # "Hirakud"
  - "harangi"
  - "bhadra"
  - "hemavathy"
  - "lower_bhawani"
  - "krishnaraja_sagar"
target_var: "volume_bcm"                          # "adjusted_level"
history_variables: ["tp", "t2m", "volume_bcm"]    # ["ndwi_all", "snow_all", "adjusted_level"]
forecast_variables: ["tp", "t2m"]
train_start_date: "2010-01-01"                    # "2010-01-01"
train_end_date: "2018-06-01"                      # "2018-12-31"
test_start_date: "2019-01-01"                     # "2019-01-01"
test_end_date: "2022-01-01"                       # "2022-01-01"

# Model Parameters
hidden_size: 64
num_layers: 1
dropout: 0.4

# Training Parameters
num_workers: 4
random_val_split: false
eval_test: false
batch_size: 100
n_epochs: 100
validate_every_n: 3
